[project]
name = 'Tokenized-Real-Estate-Transaction-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.closing-documentation]
path = 'contracts/closing-documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership-tracking]
path = 'contracts/ownership-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-verification]
path = 'contracts/property-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
